// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { AccountAskPasswordData, AccountAskPasswordResponses, AccountAskPasswordErrors, AccountLoginData, AccountLoginResponses, AccountMyselfRetrieveData, AccountMyselfRetrieveResponses, AccountResetPasswordData, AccountResetPasswordResponses, AccountResetPasswordErrors, CategoryGroupListData, CategoryGroupListResponses, CategoryGroupList2Data, CategoryGroupList2Responses, CategoryGroupList3Data, CategoryGroupList3Responses, CategoryGroupList4Data, CategoryGroupList4Responses, CategoryGroupList5Data, CategoryGroupList5Responses, CategoryGroupList6Data, CategoryGroupList6Responses, EquipmentCategoryListData, EquipmentCategoryListResponses, EquipmentCategoryList2Data, EquipmentCategoryList2Responses, EquipmentCategoryList3Data, EquipmentCategoryList3Responses, EquipmentCategoryList4Data, EquipmentCategoryList4Responses, EquipmentCategoryList5Data, EquipmentCategoryList5Responses, EquipmentCategoryList6Data, EquipmentCategoryList6Responses, EquipmentListData, EquipmentListResponses, EquipmentList2Data, EquipmentList2Responses, EquipmentList3Data, EquipmentList3Responses, EquipmentList4Data, EquipmentList4Responses, EquipmentList5Data, EquipmentList5Responses, EquipmentList6Data, EquipmentList6Responses, ReservationListData, ReservationListResponses, ReservationList2Data, ReservationList2Responses, ReservationList3Data, ReservationList3Responses, ReservationList4Data, ReservationList4Responses, ReservationList5Data, ReservationList5Responses, ReservationList6Data, ReservationList6Responses, SchemaRetrieveData, SchemaRetrieveResponses, UsersListData, UsersListResponses, UsersCreateData, UsersCreateResponses, UsersDestroyData, UsersDestroyResponses, UsersRetrieveData, UsersRetrieveResponses, UsersPartialUpdateData, UsersPartialUpdateResponses, UsersUpdateData, UsersUpdateResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Ask for password reset by sending a link to the user's email.
 */
export const accountAskPassword = <ThrowOnError extends boolean = false>(options: Options<AccountAskPasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AccountAskPasswordResponses, AccountAskPasswordErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/account/ask_password/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Login user and return authentication token.
 */
export const accountLogin = <ThrowOnError extends boolean = false>(options: Options<AccountLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AccountLoginResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/account/login/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const accountMyselfRetrieve = <ThrowOnError extends boolean = false>(options?: Options<AccountMyselfRetrieveData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AccountMyselfRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/account/myself/',
        ...options
    });
};

/**
 * Reset user password using the provided email token.
 */
export const accountResetPassword = <ThrowOnError extends boolean = false>(options: Options<AccountResetPasswordData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AccountResetPasswordResponses, AccountResetPasswordErrors, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/account/reset_password/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all category groups (public endpoint) or edit them if you are an admin.
 */
export const categoryGroupList = <ThrowOnError extends boolean = false>(options?: Options<CategoryGroupListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CategoryGroupListResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/category-groups/',
        ...options
    });
};

/**
 * List all category groups (public endpoint) or edit them if you are an admin.
 */
export const categoryGroupList2 = <ThrowOnError extends boolean = false>(options: Options<CategoryGroupList2Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<CategoryGroupList2Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/category-groups/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all category groups (public endpoint) or edit them if you are an admin.
 */
export const categoryGroupList3 = <ThrowOnError extends boolean = false>(options: Options<CategoryGroupList3Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<CategoryGroupList3Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/category-groups/{id}/',
        ...options
    });
};

/**
 * List all category groups (public endpoint) or edit them if you are an admin.
 */
export const categoryGroupList4 = <ThrowOnError extends boolean = false>(options: Options<CategoryGroupList4Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<CategoryGroupList4Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/category-groups/{id}/',
        ...options
    });
};

/**
 * List all category groups (public endpoint) or edit them if you are an admin.
 */
export const categoryGroupList5 = <ThrowOnError extends boolean = false>(options: Options<CategoryGroupList5Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<CategoryGroupList5Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/category-groups/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all category groups (public endpoint) or edit them if you are an admin.
 */
export const categoryGroupList6 = <ThrowOnError extends boolean = false>(options: Options<CategoryGroupList6Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<CategoryGroupList6Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/category-groups/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all equipment categories (public endpoint) or edit them if you are an admin.
 */
export const equipmentCategoryList = <ThrowOnError extends boolean = false>(options?: Options<EquipmentCategoryListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<EquipmentCategoryListResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipment-categories/',
        ...options
    });
};

/**
 * List all equipment categories (public endpoint) or edit them if you are an admin.
 */
export const equipmentCategoryList2 = <ThrowOnError extends boolean = false>(options: Options<EquipmentCategoryList2Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<EquipmentCategoryList2Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipment-categories/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all equipment categories (public endpoint) or edit them if you are an admin.
 */
export const equipmentCategoryList3 = <ThrowOnError extends boolean = false>(options: Options<EquipmentCategoryList3Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<EquipmentCategoryList3Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipment-categories/{id}/',
        ...options
    });
};

/**
 * List all equipment categories (public endpoint) or edit them if you are an admin.
 */
export const equipmentCategoryList4 = <ThrowOnError extends boolean = false>(options: Options<EquipmentCategoryList4Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<EquipmentCategoryList4Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipment-categories/{id}/',
        ...options
    });
};

/**
 * List all equipment categories (public endpoint) or edit them if you are an admin.
 */
export const equipmentCategoryList5 = <ThrowOnError extends boolean = false>(options: Options<EquipmentCategoryList5Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<EquipmentCategoryList5Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipment-categories/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all equipment categories (public endpoint) or edit them if you are an admin.
 */
export const equipmentCategoryList6 = <ThrowOnError extends boolean = false>(options: Options<EquipmentCategoryList6Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<EquipmentCategoryList6Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipment-categories/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all equipments (public endpoint) or edit them if you are an admin.
 */
export const equipmentList = <ThrowOnError extends boolean = false>(options?: Options<EquipmentListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<EquipmentListResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipments/',
        ...options
    });
};

/**
 * List all equipments (public endpoint) or edit them if you are an admin.
 */
export const equipmentList2 = <ThrowOnError extends boolean = false>(options: Options<EquipmentList2Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<EquipmentList2Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipments/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all equipments (public endpoint) or edit them if you are an admin.
 */
export const equipmentList3 = <ThrowOnError extends boolean = false>(options: Options<EquipmentList3Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<EquipmentList3Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipments/{serial_number}/',
        ...options
    });
};

/**
 * List all equipments (public endpoint) or edit them if you are an admin.
 */
export const equipmentList4 = <ThrowOnError extends boolean = false>(options: Options<EquipmentList4Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<EquipmentList4Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipments/{serial_number}/',
        ...options
    });
};

/**
 * List all equipments (public endpoint) or edit them if you are an admin.
 */
export const equipmentList5 = <ThrowOnError extends boolean = false>(options: Options<EquipmentList5Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<EquipmentList5Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipments/{serial_number}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List all equipments (public endpoint) or edit them if you are an admin.
 */
export const equipmentList6 = <ThrowOnError extends boolean = false>(options: Options<EquipmentList6Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<EquipmentList6Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/equipments/{serial_number}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List current user's reservations and create new ones (authenticated users only)
 */
export const reservationList = <ThrowOnError extends boolean = false>(options?: Options<ReservationListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ReservationListResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/reservations/',
        ...options
    });
};

/**
 * List current user's reservations and create new ones (authenticated users only)
 */
export const reservationList2 = <ThrowOnError extends boolean = false>(options: Options<ReservationList2Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ReservationList2Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/reservations/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List current user's reservations and create new ones (authenticated users only)
 */
export const reservationList3 = <ThrowOnError extends boolean = false>(options: Options<ReservationList3Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<ReservationList3Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/reservations/{id}/',
        ...options
    });
};

/**
 * List current user's reservations and create new ones (authenticated users only)
 */
export const reservationList4 = <ThrowOnError extends boolean = false>(options: Options<ReservationList4Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<ReservationList4Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/reservations/{id}/',
        ...options
    });
};

/**
 * List current user's reservations and create new ones (authenticated users only)
 */
export const reservationList5 = <ThrowOnError extends boolean = false>(options: Options<ReservationList5Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<ReservationList5Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/reservations/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * List current user's reservations and create new ones (authenticated users only)
 */
export const reservationList6 = <ThrowOnError extends boolean = false>(options: Options<ReservationList6Data, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<ReservationList6Responses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/reservations/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * OpenApi3 schema for this API. Format can be selected via content negotiation.
 *
 * - YAML: application/vnd.oai.openapi
 * - JSON: application/vnd.oai.openapi+json
 */
export const schemaRetrieve = <ThrowOnError extends boolean = false>(options?: Options<SchemaRetrieveData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<SchemaRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/schema/',
        ...options
    });
};

export const usersList = <ThrowOnError extends boolean = false>(options?: Options<UsersListData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UsersListResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options
    });
};

export const usersCreate = <ThrowOnError extends boolean = false>(options: Options<UsersCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UsersCreateResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/users/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const usersDestroy = <ThrowOnError extends boolean = false>(options: Options<UsersDestroyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<UsersDestroyResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const usersRetrieve = <ThrowOnError extends boolean = false>(options: Options<UsersRetrieveData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UsersRetrieveResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options
    });
};

export const usersPartialUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersPartialUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UsersPartialUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const usersUpdate = <ThrowOnError extends boolean = false>(options: Options<UsersUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UsersUpdateResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/users/{id}/',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};