// This file is auto-generated by @hey-api/openapi-ts

export type AskPassword = {
    email: string;
};

export type CategoryGroup = {
    readonly id: number;
    name: string;
    readonly created_at: string;
    readonly updated_at: string;
};

export type Equipment = {
    serial_number: string;
    name: string;
    description?: string | null;
    note?: string | null;
    status?: StatusEnum;
    readonly created_at: string;
    readonly updated_at: string;
    category: number;
};

export type EquipmentCategory = {
    readonly id: number;
    name: string;
    readonly created_at: string;
    readonly updated_at: string;
    group: number;
};

export type Login = {
    email: string;
    password: string;
};

export type PatchedCategoryGroup = {
    readonly id?: number;
    name?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
};

export type PatchedEquipment = {
    serial_number?: string;
    name?: string;
    description?: string | null;
    note?: string | null;
    status?: StatusEnum;
    readonly created_at?: string;
    readonly updated_at?: string;
    category?: number;
};

export type PatchedEquipmentCategory = {
    readonly id?: number;
    name?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
    group?: number;
};

export type PatchedReservation = {
    readonly id?: number;
    start_date?: string;
    end_date?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
    equipment?: string;
    user?: number;
};

export type PatchedUser = {
    readonly id?: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username?: string;
    /**
     * Email address
     */
    email?: string;
    first_name?: string;
    last_name?: string;
    /**
     * Staff status
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Active
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
};

export type Reservation = {
    readonly id: number;
    start_date: string;
    end_date: string;
    readonly created_at: string;
    readonly updated_at: string;
    equipment: string;
    user: number;
};

export type ResetPassword = {
    password: string;
};

/**
 * * `available` - Available
 * * `unavailable` - Unavailable
 * * `hidden` - Hidden
 */
export type StatusEnum = 'available' | 'unavailable' | 'hidden';

export type Token = {
    token: string;
};

export type User = {
    readonly id: number;
    /**
     * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
     */
    username: string;
    /**
     * Email address
     */
    email?: string;
    first_name?: string;
    last_name?: string;
    /**
     * Staff status
     * Designates whether the user can log into this admin site.
     */
    is_staff?: boolean;
    /**
     * Active
     * Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
     */
    is_active?: boolean;
};

export type AccountAskPasswordData = {
    body: AskPassword;
    path?: never;
    query?: never;
    url: '/api/account/ask_password/';
};

export type AccountAskPasswordErrors = {
    404: unknown;
};

export type AccountAskPasswordResponses = {
    200: unknown;
};

export type AccountLoginData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/api/account/login/';
};

export type AccountLoginResponses = {
    200: Token;
};

export type AccountLoginResponse = AccountLoginResponses[keyof AccountLoginResponses];

export type AccountMyselfRetrieveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/account/myself/';
};

export type AccountMyselfRetrieveResponses = {
    200: User;
};

export type AccountMyselfRetrieveResponse = AccountMyselfRetrieveResponses[keyof AccountMyselfRetrieveResponses];

export type AccountResetPasswordData = {
    body: ResetPassword;
    path?: never;
    query?: never;
    url: '/api/account/reset_password/';
};

export type AccountResetPasswordErrors = {
    404: unknown;
};

export type AccountResetPasswordResponses = {
    200: unknown;
};

export type CategoryGroupListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/category-groups/';
};

export type CategoryGroupListResponses = {
    200: Array<CategoryGroup>;
};

export type CategoryGroupListResponse = CategoryGroupListResponses[keyof CategoryGroupListResponses];

export type CategoryGroupList2Data = {
    body: CategoryGroup;
    path?: never;
    query?: never;
    url: '/api/category-groups/';
};

export type CategoryGroupList2Responses = {
    201: CategoryGroup;
};

export type CategoryGroupList2Response = CategoryGroupList2Responses[keyof CategoryGroupList2Responses];

export type CategoryGroupList3Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this category group.
         */
        id: number;
    };
    query?: never;
    url: '/api/category-groups/{id}/';
};

export type CategoryGroupList3Responses = {
    /**
     * No response body
     */
    204: void;
};

export type CategoryGroupList3Response = CategoryGroupList3Responses[keyof CategoryGroupList3Responses];

export type CategoryGroupList4Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this category group.
         */
        id: number;
    };
    query?: never;
    url: '/api/category-groups/{id}/';
};

export type CategoryGroupList4Responses = {
    200: CategoryGroup;
};

export type CategoryGroupList4Response = CategoryGroupList4Responses[keyof CategoryGroupList4Responses];

export type CategoryGroupList5Data = {
    body?: PatchedCategoryGroup;
    path: {
        /**
         * A unique integer value identifying this category group.
         */
        id: number;
    };
    query?: never;
    url: '/api/category-groups/{id}/';
};

export type CategoryGroupList5Responses = {
    200: CategoryGroup;
};

export type CategoryGroupList5Response = CategoryGroupList5Responses[keyof CategoryGroupList5Responses];

export type CategoryGroupList6Data = {
    body: CategoryGroup;
    path: {
        /**
         * A unique integer value identifying this category group.
         */
        id: number;
    };
    query?: never;
    url: '/api/category-groups/{id}/';
};

export type CategoryGroupList6Responses = {
    200: CategoryGroup;
};

export type CategoryGroupList6Response = CategoryGroupList6Responses[keyof CategoryGroupList6Responses];

export type EquipmentCategoryListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/equipment-categories/';
};

export type EquipmentCategoryListResponses = {
    200: Array<EquipmentCategory>;
};

export type EquipmentCategoryListResponse = EquipmentCategoryListResponses[keyof EquipmentCategoryListResponses];

export type EquipmentCategoryList2Data = {
    body: EquipmentCategory;
    path?: never;
    query?: never;
    url: '/api/equipment-categories/';
};

export type EquipmentCategoryList2Responses = {
    201: EquipmentCategory;
};

export type EquipmentCategoryList2Response = EquipmentCategoryList2Responses[keyof EquipmentCategoryList2Responses];

export type EquipmentCategoryList3Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this equipment category.
         */
        id: number;
    };
    query?: never;
    url: '/api/equipment-categories/{id}/';
};

export type EquipmentCategoryList3Responses = {
    /**
     * No response body
     */
    204: void;
};

export type EquipmentCategoryList3Response = EquipmentCategoryList3Responses[keyof EquipmentCategoryList3Responses];

export type EquipmentCategoryList4Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this equipment category.
         */
        id: number;
    };
    query?: never;
    url: '/api/equipment-categories/{id}/';
};

export type EquipmentCategoryList4Responses = {
    200: EquipmentCategory;
};

export type EquipmentCategoryList4Response = EquipmentCategoryList4Responses[keyof EquipmentCategoryList4Responses];

export type EquipmentCategoryList5Data = {
    body?: PatchedEquipmentCategory;
    path: {
        /**
         * A unique integer value identifying this equipment category.
         */
        id: number;
    };
    query?: never;
    url: '/api/equipment-categories/{id}/';
};

export type EquipmentCategoryList5Responses = {
    200: EquipmentCategory;
};

export type EquipmentCategoryList5Response = EquipmentCategoryList5Responses[keyof EquipmentCategoryList5Responses];

export type EquipmentCategoryList6Data = {
    body: EquipmentCategory;
    path: {
        /**
         * A unique integer value identifying this equipment category.
         */
        id: number;
    };
    query?: never;
    url: '/api/equipment-categories/{id}/';
};

export type EquipmentCategoryList6Responses = {
    200: EquipmentCategory;
};

export type EquipmentCategoryList6Response = EquipmentCategoryList6Responses[keyof EquipmentCategoryList6Responses];

export type EquipmentListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/equipments/';
};

export type EquipmentListResponses = {
    200: Array<Equipment>;
};

export type EquipmentListResponse = EquipmentListResponses[keyof EquipmentListResponses];

export type EquipmentList2Data = {
    body: Equipment;
    path?: never;
    query?: never;
    url: '/api/equipments/';
};

export type EquipmentList2Responses = {
    201: Equipment;
};

export type EquipmentList2Response = EquipmentList2Responses[keyof EquipmentList2Responses];

export type EquipmentList3Data = {
    body?: never;
    path: {
        /**
         * A unique value identifying this equipment.
         */
        serial_number: string;
    };
    query?: never;
    url: '/api/equipments/{serial_number}/';
};

export type EquipmentList3Responses = {
    /**
     * No response body
     */
    204: void;
};

export type EquipmentList3Response = EquipmentList3Responses[keyof EquipmentList3Responses];

export type EquipmentList4Data = {
    body?: never;
    path: {
        /**
         * A unique value identifying this equipment.
         */
        serial_number: string;
    };
    query?: never;
    url: '/api/equipments/{serial_number}/';
};

export type EquipmentList4Responses = {
    200: Equipment;
};

export type EquipmentList4Response = EquipmentList4Responses[keyof EquipmentList4Responses];

export type EquipmentList5Data = {
    body?: PatchedEquipment;
    path: {
        /**
         * A unique value identifying this equipment.
         */
        serial_number: string;
    };
    query?: never;
    url: '/api/equipments/{serial_number}/';
};

export type EquipmentList5Responses = {
    200: Equipment;
};

export type EquipmentList5Response = EquipmentList5Responses[keyof EquipmentList5Responses];

export type EquipmentList6Data = {
    body: Equipment;
    path: {
        /**
         * A unique value identifying this equipment.
         */
        serial_number: string;
    };
    query?: never;
    url: '/api/equipments/{serial_number}/';
};

export type EquipmentList6Responses = {
    200: Equipment;
};

export type EquipmentList6Response = EquipmentList6Responses[keyof EquipmentList6Responses];

export type ReservationListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/reservations/';
};

export type ReservationListResponses = {
    200: Array<Reservation>;
};

export type ReservationListResponse = ReservationListResponses[keyof ReservationListResponses];

export type ReservationList2Data = {
    body: Reservation;
    path?: never;
    query?: never;
    url: '/api/reservations/';
};

export type ReservationList2Responses = {
    201: Reservation;
};

export type ReservationList2Response = ReservationList2Responses[keyof ReservationList2Responses];

export type ReservationList3Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this reservation.
         */
        id: number;
    };
    query?: never;
    url: '/api/reservations/{id}/';
};

export type ReservationList3Responses = {
    /**
     * No response body
     */
    204: void;
};

export type ReservationList3Response = ReservationList3Responses[keyof ReservationList3Responses];

export type ReservationList4Data = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this reservation.
         */
        id: number;
    };
    query?: never;
    url: '/api/reservations/{id}/';
};

export type ReservationList4Responses = {
    200: Reservation;
};

export type ReservationList4Response = ReservationList4Responses[keyof ReservationList4Responses];

export type ReservationList5Data = {
    body?: PatchedReservation;
    path: {
        /**
         * A unique integer value identifying this reservation.
         */
        id: number;
    };
    query?: never;
    url: '/api/reservations/{id}/';
};

export type ReservationList5Responses = {
    200: Reservation;
};

export type ReservationList5Response = ReservationList5Responses[keyof ReservationList5Responses];

export type ReservationList6Data = {
    body: Reservation;
    path: {
        /**
         * A unique integer value identifying this reservation.
         */
        id: number;
    };
    query?: never;
    url: '/api/reservations/{id}/';
};

export type ReservationList6Responses = {
    200: Reservation;
};

export type ReservationList6Response = ReservationList6Responses[keyof ReservationList6Responses];

export type SchemaRetrieveData = {
    body?: never;
    path?: never;
    query?: {
        format?: 'json' | 'yaml';
        lang?: 'af' | 'ar' | 'ar-dz' | 'ast' | 'az' | 'be' | 'bg' | 'bn' | 'br' | 'bs' | 'ca' | 'ckb' | 'cs' | 'cy' | 'da' | 'de' | 'dsb' | 'el' | 'en' | 'en-au' | 'en-gb' | 'eo' | 'es' | 'es-ar' | 'es-co' | 'es-mx' | 'es-ni' | 'es-ve' | 'et' | 'eu' | 'fa' | 'fi' | 'fr' | 'fy' | 'ga' | 'gd' | 'gl' | 'he' | 'hi' | 'hr' | 'hsb' | 'hu' | 'hy' | 'ia' | 'id' | 'ig' | 'io' | 'is' | 'it' | 'ja' | 'ka' | 'kab' | 'kk' | 'km' | 'kn' | 'ko' | 'ky' | 'lb' | 'lt' | 'lv' | 'mk' | 'ml' | 'mn' | 'mr' | 'ms' | 'my' | 'nb' | 'ne' | 'nl' | 'nn' | 'os' | 'pa' | 'pl' | 'pt' | 'pt-br' | 'ro' | 'ru' | 'sk' | 'sl' | 'sq' | 'sr' | 'sr-latn' | 'sv' | 'sw' | 'ta' | 'te' | 'tg' | 'th' | 'tk' | 'tr' | 'tt' | 'udm' | 'ug' | 'uk' | 'ur' | 'uz' | 'vi' | 'zh-hans' | 'zh-hant';
    };
    url: '/api/schema/';
};

export type SchemaRetrieveResponses = {
    200: {
        [key: string]: unknown;
    };
};

export type SchemaRetrieveResponse = SchemaRetrieveResponses[keyof SchemaRetrieveResponses];

export type UsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersListResponses = {
    200: Array<User>;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UsersCreateData = {
    body: User;
    path?: never;
    query?: never;
    url: '/api/users/';
};

export type UsersCreateResponses = {
    201: User;
};

export type UsersCreateResponse = UsersCreateResponses[keyof UsersCreateResponses];

export type UsersDestroyData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersDestroyResponses = {
    /**
     * No response body
     */
    204: void;
};

export type UsersDestroyResponse = UsersDestroyResponses[keyof UsersDestroyResponses];

export type UsersRetrieveData = {
    body?: never;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersRetrieveResponses = {
    200: User;
};

export type UsersRetrieveResponse = UsersRetrieveResponses[keyof UsersRetrieveResponses];

export type UsersPartialUpdateData = {
    body?: PatchedUser;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersPartialUpdateResponses = {
    200: User;
};

export type UsersPartialUpdateResponse = UsersPartialUpdateResponses[keyof UsersPartialUpdateResponses];

export type UsersUpdateData = {
    body: User;
    path: {
        /**
         * A unique integer value identifying this user.
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}/';
};

export type UsersUpdateResponses = {
    200: User;
};

export type UsersUpdateResponse = UsersUpdateResponses[keyof UsersUpdateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};