/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/belt.glb --transform --keepmeshes --types --output app/components/canvas/assets/belt-2.tsx 
Files: public/assets/models/belt.glb [9.01KB] > /Users/akingram/Code/803z/web-client/app/components/canvas/assets/belt-transformed.glb [2.42KB] (73%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
  }
  materials: {
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/belt-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.015']} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.016']} />
    </group>
  )
}

useGLTF.preload('/belt-transformed.glb')
