/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/belt.glb --transform --keepmeshes --types --output app/components/canvas/assets/belt.tsx 
Files: public/assets/models/belt.glb [4.58KB] > /Users/akingram/Code/803z/web-client/app/components/canvas/assets/belt-transformed.glb [2.15KB] (53%)
*/

import * as THREE from 'three'
import { useEffect, useMemo, useRef, useState, type JSX } from 'react'
import { GradientTexture, Outlines, useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { useFrame, useLoader } from '@react-three/fiber'
import { animate } from 'framer-motion'

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh
    Cube001_1: THREE.Mesh
  }
  materials: {
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

interface ModelProps {
  animate?: boolean;
}


export function Model(props: ModelProps & JSX.IntrinsicElements['group']) {
  const { materials, nodes } = useGLTF('/assets/models/belt.glb') as unknown as GLTFResult

  const tex = useLoader(THREE.TextureLoader, "/assets/textures/Conveyor.png");
  const texClone = useMemo(() => tex.clone(), [tex]);
  const matRef = useRef<THREE.MeshStandardMaterial>(null);
  const [speed, setSpeed] = useState(0);

  useEffect(() => {
    if(!texClone) return;
    texClone.wrapS = THREE.RepeatWrapping
    texClone.wrapT = THREE.RepeatWrapping
    texClone.magFilter = THREE.NearestFilter
    texClone.minFilter = THREE.NearestFilter
    texClone.repeat.set(1, 3.264)
    texClone.flipY = false;
  }, [texClone]);

  useFrame((state, delta) => {
    if(props.animate) {
      setSpeed(1.15);
    }
    else if (speed){
      setSpeed(Math.max(0, speed - 0.02))
    }
    if(speed) {
      texClone.offset.y -= speed * delta % 1;
      texClone.offset.x += speed * delta % 1;
    }
  })
  // const texture = useTexture("assets/textures/normal.jpg");

  
  // const stripedMat = useRef<THREE.MeshStandardMaterial>(null)
  // const texture = useMemo(() => createStripedTexture(), []);
  
  // useEffect(() => {
  //   if(!stripedMat.current) return;
  //   stripedMat.current.map = createStripedTexture();
  //   stripedMat.current.needsUpdate = true;
  // }, [stripedMat]);
  
  // useFrame((_, delta) => {
  //   if(!stripedMat.current?.map) return;
  //   stripedMat.current.map.offset.x += delta;
  // });
  
  return (
    <group {...props} dispose={null}>
      <group position={[0, .75, 0]} rotation={[Math.PI, 0, 0]} receiveShadow>
        {/* <Outlines thickness={3} color="black" /> */}
        <mesh geometry={nodes.Cube001.geometry} castShadow receiveShadow>
          <meshStandardMaterial ref={matRef} map={texClone} />
          {/* <meshStandardMaterial
            ref={stripedMat}
            map={texture}
          /> */}
          {/* <Outlines thickness={3} color="black" /> */}
        </mesh>
        <mesh geometry={nodes.Cube001_1.geometry} castShadow receiveShadow material={materials['Material.016']}>
          <meshStandardMaterial 
            color="white"
          />
          {/* <meshBasicMaterial>
            <GradientTexture
              stops={[0, 1]} // As many stops as you want
              colors={['red', 'yellow']} // Colors need to match the number of stops
              size={64} // Size is optional, default = 1024
              rotation={-(Math.PI / 8) * 4}
            />
          </meshBasicMaterial> */}
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/belt.glb')
