/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/door.glb --transform --keepmeshes --types --output app/components/canvas/assets/door.tsx 
Files: public/assets/models/door.glb [1.98KB] > /Users/akingram/Code/803z/web-client/app/components/canvas/assets/door-transformed.glb [1.18KB] (40%)
*/

import * as THREE from 'three'
import React, { useEffect, useState, type JSX } from 'react'
import { Cylinder, useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import { animate, useMotionValue } from 'framer-motion'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    door: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

interface DoorProps {
  mirror?: boolean;
  isOpen: boolean;
}

export function Model(props: DoorProps & JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/door.glb') as unknown as GLTFResult
  const mirrorFactor = props.mirror ? -1 : 1;

  const [rotation, setRotation] = useState(0);

  // 1. Create the value
  const doorAngle = useMotionValue(0);

  // 2. Animate the value when 'isOpen' changes
  useEffect(() => {
      const controls = animate(doorAngle, props.isOpen ? Math.PI / 2 : 0, 
      {
          type: "spring",
          stiffness: 30,
          damping: 12
      })
      return controls.stop
  }, [props.isOpen])

  // 3. Apply the value to the standard Three.js rotation every frame
  useFrame(() => {
      setRotation(doorAngle.get());
  })
  
  return (
    <group {...props} rotation={[0, 0, 0]}>
      <group position={[-0.45 * mirrorFactor, .5, .4]}  rotation={[0, -rotation * mirrorFactor, 0]} dispose={null}>
        <mesh position={[0.45 * mirrorFactor, 0.0, 0]} geometry={nodes.door.geometry} material={materials['Material.002']}>
          {props.children}
        </mesh>
        <Cylinder args={[0.05, 0.05, .05, 10]} position={[mirrorFactor * 0.8, 1.25, .05]} rotation={[0, Math.PI / 2, Math.PI / 2]} receiveShadow>
            <meshStandardMaterial color={"#555555"} emissive={props.isOpen ? "white" : "#000000"}/>
        </Cylinder>
      </group>
    </group>
  )
}

useGLTF.preload('/assets/models/door.glb')
