/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/803Z_logo.glb --transform --keepmeshes --types --output app/components/canvas/assets/logo.tsx 
Files: public/assets/models/803Z_logo.glb [869.72KB] > /Users/akingram/Code/803z/web-client/app/components/canvas/assets/803Z_logo-transformed.glb [42.24KB] (95%)
*/

import * as THREE from 'three'
import React, { type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    character_eight: THREE.Mesh
    character_three: THREE.Mesh
    character_zed: THREE.Mesh
    character_zero: THREE.Mesh
  }
  materials: {
    black_material: THREE.MeshStandardMaterial
  }
}

export function CharacterEight(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/803Z_logo-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_eight.geometry} position={[-0.545, 0.063, 0]} castShadow receiveShadow>
        {props.children}
      </mesh>
    </group>
  )
}

export function CharacterThree(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/803Z_logo-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_three.geometry} position={[0.202, 0.063, 0]} castShadow receiveShadow>
        {props.children}
      </mesh>
    </group>
  )
}

export function CharacterZed(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/803Z_logo-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_zed.geometry} position={[0.573, 0.063, 0]} castShadow receiveShadow>
        {props.children}
      </mesh>
    </group>
  )
}

export function CharacterZero(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/803Z_logo-transformed.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.character_zero.geometry} position={[-0.169, 0.062, 0.005]} castShadow receiveShadow>
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/assets/models/803Z_logo-transformed.glb')
