/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef, type JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve002: THREE.Mesh
  }
  materials: {
    ['SVGMat.003']: THREE.MeshStandardMaterial
  }
}

export function LogoModel(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/logo.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Curve002.geometry}
        // material={materials['SVGMat.003']}
      >
        {props.children}
      </mesh>
    </group>
  )
}

useGLTF.preload('/3D_logo.glb')
