/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/models/storage.glb --transform --keepmeshes --types --output app/components/canvas/assets/storage.tsx 
Files: public/assets/models/storage.glb [6.95KB] > /Users/akingram/Code/803z/web-client/app/components/canvas/assets/storage-transformed.glb [2.14KB] (69%)
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'
import type { JSX } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube_1: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/models/storage.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material}>
        {props.children}
      </mesh>
      <mesh geometry={nodes.Cube_1.geometry} material={materials['Material.001']} />
    </group>
  )
}

useGLTF.preload('/assets/models/storage.glb')
